env:
  es6: y
  node: y
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2019
rules:
  arrow-parens: 2
  brace-style: 2
  comma-dangle: 2
  curly: 2
  indent: [2, 2, SwitchCase: 1]
  max-len: 2
  max-statements-per-line: 2
  no-multiple-empty-lines: [2, max: 1]
  no-param-reassign: 2
  quotes: [2, single]
  semi: 2
