env:
  es6: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2019
rules:
  arrow-parens: error
  curly: error
  indent: [error, 2, SwitchCase: 1]
  max-len: error
  max-statements-per-line: error
  no-multiple-empty-lines: [2, max: 1]
  quotes: [error, single]
  semi: error
  sort-keys: [2, asc, caseSensitive: false]
  sort-vars: [2, ignoreCase: true]
