env:
  es6: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2019
rules:
  arrow-parens: 2
  brace-style: 2
  comma-dangle: 2
  curly: 2
  indent:
    - 2
    - 2
  max-len: 2
  max-statements-per-line: 2
  newline-per-chained-call:
    - 2
    - ignoreChainWithDepth: 1
  no-multiple-empty-lines:
    - 2
    - max: 1
  quotes: 2
  semi: 2
