env:
  es6: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2019
rules:
  arrow-parens: error
  curly: error
  indent: [error, 2, SwitchCase: 1]
  max-len: error
  max-statements-per-line: error
  no-multiple-empty-lines: [error, max: 1]
  quotes: [error, single]
  semi: error
  sort-keys: [error, asc, caseSensitive: false]
  sort-vars: [error, ignoreCase: true]
